### ISSUE TITLE
Noisy mode-line

### ISSUE THREAD

**Issue by hpdeifel** [joaotavora/eglot#236]
Eglot shows the status of the language server in the mode-line, which for some servers can change very rapidly while typing. For example with `rls`, the status often constantly alternates between "Building",  "Indexing" and "n outstanding requests".

To me, this constant flickering at the bottom of the screen is quite distracting and I'd like to have an option to remove this volatile information from the mode-line. I'm still interested in the workspace name and possible errors.

For what it's worth, flymake also has a quite noisy mode-line lighter, but it's easy to just diminish that.

**Comment by joaotavora** [comment]
@hpdeifel, @ambihelical I pushed a commit that should improve the situation and not add too much confusing defcustoms.  Feel free to comment.

**Comment by hpdeifel** [comment]
Yes, it's better now. Thanks!

**Comment by simurgh9** [comment]
I am still getting a lot of "building" messages in Java files. Any help?

**Comment by joaotavora** [comment]
It's been three and a half years. 🤣  i guess this is why she projects lock old issues.

Anyway, you have to give some context, like what messages exactly and which version of Eglot you are using. A three year-old one?

Eglot now has the `eglot-report-progress` variable to control this.

**Comment by simurgh9** [comment]
![Noisy minibuffer](https://i.stack.imgur.com/Y7LEZ.gif)

The source code `eglot.el` says `Version: 1.10`.
