### ISSUE TITLE
incorrect textDocument/didChange with somes commands like downcase-word

### ISSUE THREAD

**Issue by Sarcasm** [joaotavora/eglot#259]
I have been using eglot + clangd for a while now, and I very often desynchronization of the editing changes, which I fix by reverting my buffers regularly.

I think it comes from incorrect `textDocument/didChange` for the following Emacs operations:
- `{downcase,capitalize,upcase}-word`

An example with the case-changing command.

Given this buffer, with the cursor being the `|` character:

```cpp
void f() {
  int foo|bar;
}
```

Type <kbd>M-c</kbd> to capitalize `bar`:

```cpp
void f() {
  int fooBar|;
}
```

The buffer is no longer synchronized, flymake is in the `Wait` state.
The `events` buffer shows:

```

client-notification Tue May  7 09:39:42 2019:
(:jsonrpc "2.0" :method "textDocument/didChange" :params
          (:textDocument
           (:uri "file:///tmp/foo.cpp" :version 19)
           :contentChanges
           [(:range
             (:start
              (:line 1 :character 9)
              :end
              (:line 1 :character 12))
             :rangeLength 1 :text "B")]))
```

This discussion https://github.com/microsoft/language-server-protocol/issues/9 seems to indicate that range start/end + rangeLength should cover the same range, which does not seem the case here.

**Comment by mkcms** [comment]
Thanks for reporting that.

Can you try this patch and see if this solves your problem?

```diff
diff --git a/eglot.el b/eglot.el
index ef0cb08..a62acfe 100644
--- a/eglot.el
+++ b/eglot.el
@@ -1547,8 +1547,16 @@ Records START, END and PRE-CHANGE-LENGTH locally."
   (cl-incf eglot--versioned-identifier)
   (if (and (listp eglot--recent-changes)
            (null (cddr (car eglot--recent-changes))))
-      (setf (cddr (car eglot--recent-changes))
-            `(,pre-change-length ,(buffer-substring-no-properties start end)))
+      (let ((new-beg (eglot--lsp-position-to-point (caar eglot--recent-changes)))
+            (new-end (eglot--lsp-position-to-point (cadar eglot--recent-changes))))
+        (when (or (and (cl-plusp pre-change-length)
+                       (zerop (- end start)))
+                  (and (zerop pre-change-length)
+                       (not (zerop (- end start)))))
+          (setq new-beg start new-end end))
+        (setf (cddr (car eglot--recent-changes))
+              `(,(- new-end new-beg)
+                ,(buffer-substring-no-properties new-beg new-end))))
     (setf eglot--recent-changes :emacs-messup))
   (when eglot--change-idle-timer (cancel-timer eglot--change-idle-timer))
   (let ((buf (current-buffer)))
@@ -1610,7 +1618,10 @@ When called interactively, use the currently active server"
                                                               (point-max)))))
           (cl-loop for (beg end len text) in (reverse eglot--recent-changes)
                    vconcat `[,(list :range `(:start ,beg :end ,end)
-                                    :rangeLength len :text text)]))))
+                                    :rangeLength
+                                    (- (eglot--lsp-position-to-point end)
+                                       (eglot--lsp-position-to-point beg))
+                                    :text text)]))))
       (setq eglot--recent-changes nil)
       (setf (eglot--spinner server) (list nil :textDocument/didChange t))
       (jsonrpc--call-deferred server))))

```

**Comment by mkcms** [comment]
Ignore the last comment. Instead, please try this branch: https://github.com/joaotavora/eglot/commit/b1a0fbb34f307a2bd65e5d360b5a1ea2e56c3bf0

**Comment by joaotavora** [comment]
@mkcms, welcome back on board! Can you explain what is going on here?

**Comment by mkcms** [comment]
Hi @joaotavora,

> welcome back on board!

I'm less active now because I'm kind of busy now, but I'll try to fix/improve some things in my free time.

> Can you explain what is going on here?

I'm not sure, I wrote the fixes above by trial and error method.


From my observation, in buffer with these contents:

```
ThisIsAString
```

When I `trace-function`s `eglot--{before,after}-change` and do `M-l` at the beginning of the buffer, I get:

```

======================================================================
1 -> (eglot--before-change 1 14)
1 <- eglot--before-change: (((:line 0 :character 0) (:line 0 :character 13)))
======================================================================
1 -> (eglot--after-change 1 9 8)
1 <- eglot--after-change: [nil 0 0 500000 nil (closure ((buf . #<buffer test.cpp>) (pre-change-length . 8) (end . 9) (start . 1) t) nil (let ((G3256 buf)) (if (buffer-live-p G3256) (save-current-buffer (set-buffer G3256) (if eglot--managed-mode (progn (eglot--signal-textDocument/didChange) (setq eglot--change-idle-timer nil))))))) nil idle 0]
```

So as you can see, the region that is passed to the `after-change` function is different than the region passed to `before-change` function. 

Both functions disagree on what changed. Is this documented Emacs behavior? Maybe I'm doing something wrong, I'll have to investigate further.

**Comment by Sarcasm** [comment]
The patch seems to work, thanks! :)

While testing, I think I found another issue:

```cpp
void f() {
  int foobar = 0|;
}
```

Type backspace 4 times to remove the assignment:
```cpp
void f() {
  int foobar|;
}
```

The resulting `textDocument/didChange`:

```cpp
client-notification Tue May  7 12:22:37 2019:
(:jsonrpc "2.0" :method "textDocument/didChange" :params
          (:textDocument
           (:uri "file:///tmp/foo.cpp" :version 4)
           :contentChanges
           [(:range
             (:start
              (:line 1 :character 15)
              :end
              (:line 1 :character 16))
             :rangeLength 0 :text "")
            (:range
             (:start
              (:line 1 :character 14)
              :end
              (:line 1 :character 15))
             :rangeLength 0 :text "")
            (:range
             (:start
              (:line 1 :character 13)
              :end
              (:line 1 :character 14))
             :rangeLength 0 :text "")
            (:range
             (:start
              (:line 1 :character 12)
              :end
              (:line 1 :character 13))
             :rangeLength 1 :text "")]))
```

If I remove the characters very slowly, I do not have the issue, and don't see any null `:rangeLength`.

**Comment by mkcms** [comment]
@Sarcasm 

> If I remove the characters very slowly, I do not have the issue, and don't see any null `:rangeLength`.

Yes, I can observe the same behavior. But this is from the earlier patch, right? It's buggy, test the branch `scratch/fix-259-attempt`.

**Comment by Sarcasm** [comment]
Ah yes sorry, just tested with the new patch, and it works great this time!

**Comment by mkcms** [comment]
@Sarcasm Thanks for testing.

I'm pinging @joaotavora to take a look at the fix, as I'm not 100% sure it is correct, and even caused by eglot itself. It might be an Emacs bug. We already caught several bugs related to modification hooks in Emacs, so it's possible:

https://debbugs.gnu.org/cgi/bugreport.cgi?bug=32237
https://debbugs.gnu.org/cgi/bugreport.cgi?bug=32278

**Comment by joaotavora** [comment]
Hi @mkcms, @Sarcasm 

I was taking a good look at this the other day but then got sidetracked.  I think the reason this started showing with `clangd` is because it started working with incremental changes from a recent version (Also maybe other servers aren't tripped by this because they can somehow infer the correct interpretation? That would be strange because it is indeed ambiguous and looks like a deletion)

Anyway, it _is_ probably an Emacs bug, but something we definitely have to work around anyway. I have come up with this simpler fix in branch `scratch/fix-259-another-attempt` @mkcms, @Sarcasm, can you test?

**Comment by joaotavora** [comment]
By the way, this is pretty serious, so pushing _some_ version that works is probably warranted. And maybe also bumping the version, so GNU Elpa catches it.

**Comment by Sarcasm** [comment]
@joaotavora : Your patch fixes the capitalize and friends issue, but deleting ` = 0` does not work, similarly to @mkcms 's first patch.

This time I get this event in the log:

```
client-notification Thu May  9 12:52:52 2019:
(:jsonrpc "2.0" :method "textDocument/didChange" :params
          (:textDocument
           (:uri "file:///tmp/foo.cpp" :version 8)
           :contentChanges
           [(:range
             (:start
              (:line 1 :character 15)
              :end
              (:line 1 :character 15))
             :rangeLength 1 :text "")
            (:range
             (:start
              (:line 1 :character 14)
              :end
              (:line 1 :character 14))
             :rangeLength 1 :text "")
            (:range
             (:start
              (:line 1 :character 13)
              :end
              (:line 1 :character 13))
             :rangeLength 1 :text "")
            (:range
             (:start
              (:line 1 :character 12)
              :end
              (:line 1 :character 12))
             :rangeLength 1 :text "")]))
```

**Comment by mkcms** [comment]
@joaotavora 
I also have issues with your branch.
In this buffer:

```
int foo() {
    int Foo = 1;
}
```

If I'm at beginning of second line and press `M-l M-m M-c` quickly, I get:

```
client-notification Thu May  9 15:43:47 2019:
(:jsonrpc "2.0" :method "textDocument/didChange" :params
	  (:textDocument
	   (:uri "file:///home/michal/src/configserver3/src/template.cc" :version 1)
	   :contentChanges
	   [(:range
	     (:start
	      (:line 1 :character 4)
	      :end
	      (:line 1 :character 7))
	     :rangeLength nil :text nil)
	    (:range
	     (:start
	      (:line 1 :character 4)
	      :end
	      (:line 1 :character 5))
	     :rangeLength 1 :text "I")]))
```

And the stderr buffer shows:

```
I[15:44:55.009] --> textDocument/publishDiagnostics
I[15:44:55.121] <-- textDocument/signatureHelp(33)
I[15:44:55.127] --> reply:textDocument/signatureHelp(33) 5 ms
I[15:44:56.196] <-- textDocument/signatureHelp(34)
I[15:44:56.200] --> reply:textDocument/signatureHelp(34) 4 ms
I[15:44:58.137] <-- textDocument/didChange
E[15:44:58.137] Failed to decode textDocument/didChange request.
```

**Comment by joaotavora** [comment]
@Sarcasm, @mkcms , can you try the latest version?

By the way, the bugs all comes from any command that uses `casify_region` in `casefiddle.c`. I wonder if that's been reported to Emacs: it's pretty bungled, and seems easy to fix.  But looks in the Emacs C code can definitely be deceiving.

**Comment by Sarcasm** [comment]
I will let @mkcms confirm, but it does not seem to work for me.

Changing case seems ok, but deleting multiple characters with backspace seems to cause issues.

start-end are equal (wrong), but rangeLength is 1 (ok).

```
client-notification Thu May  9 17:08:02 2019:
(:jsonrpc "2.0" :method "textDocument/didChange" :params
          (:textDocument
           (:uri "file:///tmp/foo.cpp" :version 8)
           :contentChanges
           [(:range
             (:start
              (:line 1 :character 15)
              :end
              (:line 1 :character 15))
             :rangeLength 1 :text "")
            (:range
             (:start
              (:line 1 :character 14)
              :end
              (:line 1 :character 14))
             :rangeLength 1 :text "")
            (:range
             (:start
              (:line 1 :character 13)
              :end
              (:line 1 :character 13))
             :rangeLength 1 :text "")
            (:range
             (:start
              (:line 1 :character 12)
              :end
              (:line 1 :character 12))
             :rangeLength 1 :text "")]))



I[17:08:02.342] <-- textDocument/didChange
E[17:08:02.342] Failed to update /tmp/foo.cpp: Change's rangeLength (1) doesn't match the computed range length (0).
I[17:08:02.344] <-- textDocument/didSave
I[17:08:02.344] unhandled notification textDocument/didSave
```

**Comment by mkcms** [comment]
@joaotavora 
If I have a buffer as in my previous comment, and quickly do `M-l M-l M-l` on the second line, I get

```

client-notification Thu May  9 17:16:13 2019:
(:jsonrpc "2.0" :method "textDocument/didChange" :params
	  (:textDocument
	   (:uri "file:///home/michal/src/configserver3/src/template.cc" :version 1)
	   :contentChanges
	   [(:range
	     (:start
	      (:line 1 :character 7)
	      :end
	      (:line 1 :character 9))
	     :rangeLength 1 :text "f")]))

I[17:16:12.008] --> reply:textDocument/signatureHelp(43) 2 ms
I[17:16:13.809] <-- textDocument/didChange
E[17:16:13.809] Failed to update /home/michal/src/configserver3/src/template.cc: Change's rangeLength (1) doesn't match the computed range length (2).
I[17:16:23.533] <-- textDocument/signatureHelp(44)
I[17:16:23.533] --> reply:textDocument/signatureHelp(44) 0 ms, error: -32602: trying to get preamble for non-added document

```

Also, when I have the same buffer, but with `int` changed to `Int` beforehand, I get:

```
client-notification Thu May  9 17:17:49 2019:
(:jsonrpc "2.0" :method "textDocument/didChange" :params
	  (:textDocument
	   (:uri "file:///home/michal/src/configserver3/src/template.cc" :version 2)
	   :contentChanges
	   [(:range
	     (:start
	      (:line 1 :character 0)
	      :end
	      (:line 1 :character 5))
	     :rangeLength 1 :text "i")
	    (:range
	     (:start
	      (:line 1 :character 7)
	      :end
	      (:line 1 :character 9))
	     :rangeLength 1 :text "f")
	    (:range
	     (:start
	      (:line 1 :character 11)
	      :end
	      (:line 1 :character 15))
	     :rangeLength nil :text nil)]))
```

**Comment by mkcms** [comment]
By the way, I wonder if there is a way that we can only use either `before-` or `after-change-functions`, because the info node `(elisp) Change Hooks` says:

>    The vast majority of buffer changing primitives will call
> ‘before-change-functions’ and ‘after-change-functions’ in balanced
> pairs, once for each change, where the arguments to these hooks exactly
> delimit the change being made.  Yet, hook functions should not rely on
> this always being the case, because some complex primitives call
> ‘before-change-functions’ once before making changes, and then call
> ‘after-change-functions’ zero or more times, depending on how many
> individual changes the primitive is making.  When that happens, the
> arguments to ‘before-change-functions’ will enclose a region in which
> the individual changes are made, but won’t necessarily be the minimal
> such region, and the arguments to each successive call of
> ‘after-change-functions’ will then delimit the part of text being
> changed exactly.  In general, we advise using either the before- or the
> after-change hook, but not both.
>

**Comment by joaotavora** [comment]
> By the way, I wonder if there is a way that we can only use either before- or after-change-functions, 

No. @monnier has asked that already and the comment in `eglot--before-change` is there exactly to answer that question.  Newlines may have been inserted/deleted and LSP needs to know the line number.

**Comment by joaotavora** [comment]
@mkcms, please try the latest version to check if it fixed your bugs (your case was related to starting a downcase before the word started).

@Sarcasm, I couldn't reproduce the backspace problem, even with the previous version.  But please try with this new one.

**Comment by mkcms** [comment]
@joaotavora 

> @mkcms, please try the latest version to check if it fixed your bugs

Again with this buffer:

```cpp
int foo() {
    int foo = 1;
}
```

If I do `C-x h C-x C-u`, I get:

```

client-notification Fri May 10 07:33:49 2019:
(:jsonrpc "2.0" :method "textDocument/didChange" :params
	  (:textDocument
	   (:uri "file:///home/michal/src/configserver3/src/template.cc" :version 1)
	   :contentChanges
	   [(:range
	     (:start
	      (:line 0 :character 0)
	      :end
	      (:line 3 :character 0))
	     :rangeLength 23 :text "INT FOO() {\n    INT FOO")]))

I[07:33:49.006] <-- textDocument/didChange
E[07:33:49.006] Failed to update /home/michal/src/configserver3/src/template.cc: Change's rangeLength (23) doesn't match the computed range length (31).
```

**Comment by mkcms** [comment]
@joaotavora 

> Newlines may have been inserted/deleted and LSP needs to know the line number.

Yes, `eglot--before-change` is necessary. But is `eglot--after-change`? Wouldn't it work if we just made markers in `eglot--before-change` and scheduled a 0-second timer which notifies the server of the changes? In the timer callback, we would have information about line numbers and the text that is between the markers. So maybe the after change function is not required.

**Comment by Sarcasm** [comment]
No issues when changing the case
However, while it's more difficult, I can get errors using the "normal" editing commands, to insert and delete characters.

FYI, I'm not sure it's relevant, but backspace is effectively `c-electric-backspace`.

I type and delete some text quickly:

```cpp
  int foo_bar|;
  int foo_bar |;
  int foo_bar =|;
  int foo_bar = 0|;
  int foo_bar = |;
  int foo_bar =|;
  int foo_bar |;
  int foo_bar|;
```

I get this logs:

```

client-notification Fri May 10 09:58:15 2019:
(:jsonrpc "2.0" :method "textDocument/didChange" :params
          (:textDocument
           (:uri "file:///tmp/foo.cpp" :version 27)
           :contentChanges
           [(:range
             (:start
              (:line 1 :character 13)
              :end
              (:line 1 :character 13))
             :rangeLength 0 :text " ")
            (:range
             (:start
              (:line 1 :character 14)
              :end
              (:line 1 :character 14))
             :rangeLength 0 :text "=")
            (:range
             (:start
              (:line 1 :character 15)
              :end
              (:line 1 :character 15))
             :rangeLength 0 :text " ")
            (:range
             (:start
              (:line 1 :character 16)
              :end
              (:line 1 :character 16))
             :rangeLength 0 :text "0")
            (:range
             (:start
              (:line 1 :character 16)
              :end
              (:line 1 :character 17))
             :rangeLength 1 :text "")
            (:range
             (:start
              (:line 1 :character 15)
              :end
              (:line 1 :character 16))
             :rangeLength 1 :text "")
            (:range
             (:start
              (:line 1 :character 14)
              :end
              (:line 1 :character 15))
             :rangeLength 1 :text "")
            (:range
             (:start
              (:line 1 :character 13)
              :end
              (:line 1 :character 14))
             :rangeLength 1 :text "")]))
```

Then stderr buffer says:

    I[09:58:16.014] Skipping rebuild of the AST for /tmp/foo.cpp, inputs are the same.

**Comment by joaotavora** [comment]
The logs for your input look fine at first glance.

> However, for some reasons, flymake seems stuck in Wait mode, until edit some more or move the cursor.

This is a different problem, which you might want to report separately.  The problem is that since a `didChange` did go out, but `clangd` detected no changes and skipped rebuilding, Eglot never got the diagnostics report: it is still `Wait`ing for it. You could argue that Eglot should also detect this, but that is a different problem...

By the way, I doubt that this `Wait` behaviour doesn't manifest in:
1. @mkcms's version
2. The current version in master.

Still, can you check 1 and 2?

**Comment by Sarcasm** [comment]
Indeed, the `Wait` issue happens in 1 and 2.
This `Wait` is what I used to see when the buffer was stuck out of sync, but I agree this is no longer the same issue, and this time it is not persistent so it's not really an issue.

However, I confirm @mkcms behavior when changing the case for the whole buffer: https://github.com/joaotavora/eglot/issues/259#issuecomment-491162237

I don't have the issue with @mkcms's version.

**Comment by joaotavora** [comment]
@mkcms 

> If I do C-x h C-x C-u, I get:

I see yes: upcasing a region fails miserably because it defeats my strategy of
1.  narrowly checking for "same line numbers"
2. If so, go with the `start` and `end` of the `after-change-functions`

If only there was some way to detect that the broken `casify_region` was involved in a particular change, I could replace 1 with it and it should start working again (because casifying doesn't ever add or remove newlines). It's horrible, but the only thing I can think of is advising all functions that call it to bind a global that Eglot can read.  This would be `{{up|down}case|capitalize}-{word|region}`.

But if "your" fix somehow gets around all this, and you have tested it sufficiently, go ahead and push that.  But make sure you comment as much as you can to explain what it is doing.

> Wouldn't it work if we just made markers in eglot--before-change and scheduled a 0-second timer

Maybe, I don't know.  I like the first part of the idea: the markers in `eglot--before-change`, but the 0-second timer is bad: we don't want a didChange for every `eglot--before-change`.  But yes, you could theoretically just use the information collected in `eglot--before-change` to grab the changed regions, and schedule the timer as is currently done in `eglot--after-change`, with the "reschedule-up-if-theres-another-change-already" mechanism.  Then, when the timer eventually does run, just compare the current text between the markers to the text information you collected (markers and engths, or maybe something else), and craft your `didChange` accordingly.

It's quite a different strategy, but it could be simpler, more correct, and even more efficient.  If you have the time, try it out.

**Comment by joaotavora** [comment]
@Sarcasm and @mkcms I've come up with a new version which uses a different detection scheme, please test again.

**Comment by joaotavora** [comment]
BTW @mkcms, After doing all this work, I am starting to understand your version from 3 days ago.  It's starting to look simpler :-) so I might very well push that later today.

**Comment by Sarcasm** [comment]
Last patch seems good! :+1:

**Comment by joaotavora** [comment]
@Sarcasm, @mkcms: I've also tweaked the original patch by @mkcms, in the `scratch/fix-259-attempt` branch to make it slightly more efficient.  If you can, please also test that.  I will push one of the patches later today.

**Comment by Sarcasm** [comment]
I think I get a different error with the new patch.

With this buffer:

```cpp
void f() {
  int |[foo_]bar;
}
```

Region is under brackets.

I comment the region:

```cpp
void f() {
  int |// foo_
    bar;
}
```

I undo, commenting was a mistake:

```cpp
void f() {
  int |foo_bar;
}
```

I get this error:

```
I[16:31:51.726] <-- textDocument/didChange
E[16:31:51.726] Failed to update /tmp/foo.cpp: UTF-16 offset 4 is invalid for line 2
```

But I think another time I got a complaint about the rangeLength not matching, so UTF-16 offset 4 may not be the interesting error.

```
client-notification Fri May 10 16:31:51 2019:
(:jsonrpc "2.0" :method "textDocument/didChange" :params
          (:textDocument
           (:uri "file:///tmp/foo.cpp" :version 2)
           :contentChanges
           [(:range
             (:start
              (:line 1 :character 6)
              :end
              (:line 2 :character 4))
             :rangeLength 12 :text "foo_")]))
```

With the previous change it does not happen.

**Comment by joaotavora** [comment]
> With the previous change it does not happen.

What change exactly does it not happen with?? The one is the "fix-259-another-attempt" branch or @mkcms's original one in the "fix-250-attempt"? Can you name the commit SHA? (Yes I do realize I am the principal author of all the confusion).

**Comment by Sarcasm** [comment]
https://github.com/joaotavora/eglot/commit/05340038c78b952c236bcb19e80bd1406ce4c7b6 :+1:
https://github.com/joaotavora/eglot/commit/15b77f2974fa8ebacfbc98d7e997db64b2cd446d :-1:

**Comment by mkcms** [comment]
@Sarcasm 
Please test again. The end marker needed to be "move-after-insertion" type, I don't know how reliable it is though.

@joaotavora  I'm in favor of only removing `eglot--after-change`. 

---

Instead of using markers, we can simply remember the lines on which `beg` and `end` are. When sending change events, we can send the buffer contents from beginning of the start-line up to end of end-line. We don't have to send these very small regions that exactly contain the changed region.

**Comment by mkcms** [comment]
@joaotavora 

> EDIT: The only drawback I see is that is seems inneficient when there are lots of "bogus" before-changes. But that's possibly a rare case.

If you mean creating lots of markers when typing characters normally, perhaps it can be optimized, for example to remember the last pair of markers created and to reuse them.

**Comment by monnier** [comment]
>> EDIT: The only drawback I see is that is seems inneficient when there are
> lots of "bogus" before-changes. But that's possibly a rare case.
>
> If you mean creating lots of markers when typing characters normally,
> perhaps it can be optimized, for example to remember the last pair of
> markers created and to reuse them.

IIUC it should be possible to use just 2 markers and an integer
(i.e. no need to create new markers).
Together they'd delimit a region that's been modified since the last time
we updated the server's copy, along with the number of lines that used
to be in that region.

**Comment by joaotavora** [comment]
> If you mean creating lots of markers when typing characters normally,

No, I didn't mean this.  I mean the case where e.g. `downcase-word` does nothing to a word (because it is already downcased) and that creates a useless "change"  that is  needlessly transmitted to the server, processed there, etc. My last commit to your branch fixes this case, but there is still the slightly less severe case that `capitalize-word` usually only changes one character of a word but still information about the whole word is transmitted, again needlessly, to the server.

That said, if you can make your branch even simpler (with @monnier's guidance), that is even better. But I wouldn't worry about reusing markers at all, it doesn't seem like an immense number of objects and they are pretty short-lived. Any decent garbage collector should make quick work of such things (alas no idea if Emacs's is such a GC...)

**Comment by joaotavora** [comment]
I pushed "my" latest version, as I'm slightly more confident in the way it works.  I'll keep the other approach at hand, though, in case I somehow messed up or in case we can get a simpler implementation altogether.

**Comment by Sarcasm** [comment]
I have updated my eglot to the master version.
Thank you all for the fix! :sparkles: 
It was really painful to have to revert my buffers all the time.

**Comment by mkcms** [comment]
@joaotavora 

Sorry for late reply.

> I pushed "my" latest version, as I'm slightly more confident in the way it works. I'll keep the other approach at hand, though, in case I somehow messed up or in case we can get a simpler implementation altogether.

It's still not fixed for me when I do what I described here: https://github.com/joaotavora/eglot/issues/259#issuecomment-491162237. I get the same behavior as described. I'm testing with `emacs -Q` and 5f629ebfb680f43849ca894c7166a2b54ff5ba50

**Comment by joaotavora** [comment]
@mkcms, thanks: are you confident that your version passes through all the hoops? If so, cleanup the commit logs and push that one, please, but do include my optimization if you can...

**Comment by mkcms** [comment]
@joaotavora Sorry for the fuss, I was confused by what I saw in the events buffer, where the `:text` was the same as in the bugged version, but the `:rangeLength` was fine though. Closing this issue.

**Comment by joaotavora** [comment]
@mkcms, yes, I couldn't reproduce it as well...

**Comment by joaotavora** [comment]
@kadircet has pointed to a new problem:  Here it is
```
namespace a { void bar(); }
void foo() {
a::bar(); // you should have a diag here saying convert bar to a::bar, apply it.
}
```
After applying, the incorrect `didChange` notification is passed to the server

**Comment by Sarcasm** [comment]
I can confirm, I regularly have issues after applying a code action.

**Comment by joaotavora** [comment]
@Sarcasm , @kadircet, should be fixed, please test when you can.

**Comment by Sarcasm** [comment]
LGTM :+1:
