### ISSUE TITLE
Error connecting to js-langserver in Emacs 27

### ISSUE THREAD

**Issue by lljr** [joaotavora/eglot#300]
I only have eglot installed at the moment (very minimal Emacs setup). 

After calling eglo on an empty `test.py` file (`M-x eglot`) I am told this error message:
```
Searching for program: No such file or directory, pyls
```

Turning on `M-x toggle-debug-on-error` prints
```
Debugger entered--Lisp error: (file-missing "Searching for program" "No such file or directory" "pyls")
  make-process(:name "EGLOT (Desktop/python-mode)" :command ("pyls") :connection-type pipe :coding utf-8-emacs-unix :noquery t :stderr #<buffer *EGLOT (Desktop/python-mode) stderr*>)
  #f(compiled-function () #<bytecode 0x4193c1bd>)()
  #f(compiled-function (cl--cnm conn slots) #<bytecode 0x419aeb81>)(#f(compiled-function (&rest cnm-args) #<bytecode 0x4193c241>) #<eglot-lsp-server eglot-lsp-server> (:name "EGLOT (Desktop/python-mode)" :events-buffer-scrollback-size 2000000 :notification-dispatcher #f(compiled-function (server method params) #<bytecode 0x4193c1d5>) :request-dispatcher #f(compiled-function (server method params) #<bytecode 0x4193c1f1>) :on-shutdown eglot--on-shutdown :process #f(compiled-function () #<bytecode 0x4193c1bd>)))
  apply(#f(compiled-function (cl--cnm conn slots) #<bytecode 0x419aeb81>) #f(compiled-function (&rest cnm-args) #<bytecode 0x4193c241>) (#<eglot-lsp-server eglot-lsp-server> (:name "EGLOT (Desktop/python-mode)" :events-buffer-scrollback-size 2000000 :notification-dispatcher #f(compiled-function (server method params) #<bytecode 0x4193c1d5>) :request-dispatcher #f(compiled-function (server method params) #<bytecode 0x4193c1f1>) :on-shutdown eglot--on-shutdown :process #f(compiled-function () #<bytecode 0x4193c1bd>))))
  #f(compiled-function (&rest args) #<bytecode 0x419acae9>)(#<eglot-lsp-server eglot-lsp-server> (:name "EGLOT (Desktop/python-mode)" :events-buffer-scrollback-size 2000000 :notification-dispatcher #f(compiled-function (server method params) #<bytecode 0x4193c1d5>) :request-dispatcher #f(compiled-function (server method params) #<bytecode 0x4193c1f1>) :on-shutdown eglot--on-shutdown :process #f(compiled-function () #<bytecode 0x4193c1bd>)))
  apply(#f(compiled-function (&rest args) #<bytecode 0x419acae9>) #<eglot-lsp-server eglot-lsp-server> (:name "EGLOT (Desktop/python-mode)" :events-buffer-scrollback-size 2000000 :notification-dispatcher #f(compiled-function (server method params) #<bytecode 0x4193c1d5>) :request-dispatcher #f(compiled-function (server method params) #<bytecode 0x4193c1f1>) :on-shutdown eglot--on-shutdown :process #f(compiled-function () #<bytecode 0x4193c1bd>)))
  initialize-instance(#<eglot-lsp-server eglot-lsp-server> (:name "EGLOT (Desktop/python-mode)" :events-buffer-scrollback-size 2000000 :notification-dispatcher #f(compiled-function (server method params) #<bytecode 0x4193c1d5>) :request-dispatcher #f(compiled-function (server method params) #<bytecode 0x4193c1f1>) :on-shutdown eglot--on-shutdown :process #f(compiled-function () #<bytecode 0x4193c1bd>)))
  #f(compiled-function (class &rest slots) "Default constructor for CLASS `eieio-default-superclass'.\nSLOTS are the initialization slots used by `initialize-instance'.\nThis static method is called when an object is constructed.\nIt allocates the vector used to represent an EIEIO object, and then\ncalls `initialize-instance' on that object." #<bytecode 0x409134df>)(eglot-lsp-server :name "EGLOT (Desktop/python-mode)" :events-buffer-scrollback-size 2000000 :notification-dispatcher #f(compiled-function (server method params) #<bytecode 0x4193c1d5>) :request-dispatcher #f(compiled-function (server method params) #<bytecode 0x4193c1f1>) :on-shutdown eglot--on-shutdown :process #f(compiled-function () #<bytecode 0x4193c1bd>))
  apply(#f(compiled-function (class &rest slots) "Default constructor for CLASS `eieio-default-superclass'.\nSLOTS are the initialization slots used by `initialize-instance'.\nThis static method is called when an object is constructed.\nIt allocates the vector used to represent an EIEIO object, and then\ncalls `initialize-instance' on that object." #<bytecode 0x409134df>) eglot-lsp-server (:name "EGLOT (Desktop/python-mode)" :events-buffer-scrollback-size 2000000 :notification-dispatcher #f(compiled-function (server method params) #<bytecode 0x4193c1d5>) :request-dispatcher #f(compiled-function (server method params) #<bytecode 0x4193c1f1>) :on-shutdown eglot--on-shutdown :process #f(compiled-function () #<bytecode 0x4193c1bd>)))
  make-instance(eglot-lsp-server :name "EGLOT (Desktop/python-mode)" :events-buffer-scrollback-size 2000000 :notification-dispatcher #f(compiled-function (server method params) #<bytecode 0x4193c1d5>) :request-dispatcher #f(compiled-function (server method params) #<bytecode 0x4193c1f1>) :on-shutdown eglot--on-shutdown :process #f(compiled-function () #<bytecode 0x4193c1bd>))
  apply(make-instance eglot-lsp-server :name "EGLOT (Desktop/python-mode)" :events-buffer-scrollback-size 2000000 :notification-dispatcher #f(compiled-function (server method params) #<bytecode 0x4193c1d5>) :request-dispatcher #f(compiled-function (server method params) #<bytecode 0x4193c1f1>) :on-shutdown eglot--on-shutdown (:process #f(compiled-function () #<bytecode 0x4193c1bd>)))
  eglot--connect(python-mode (transient . "/Users/jr/Desktop/") eglot-lsp-server ("pyls"))
  eglot(python-mode (transient . "/Users/jr/Desktop/") eglot-lsp-server ("pyls") t)
  funcall-interactively(eglot python-mode (transient . "/Users/jr/Desktop/") eglot-lsp-server ("pyls") t)
  call-interactively(eglot record nil)
  command-execute(eglot record)
  execute-extended-command(nil "eglot" "egl")
  funcall-interactively(execute-extended-command nil "eglot" "egl")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```
 Pyls is installed globally with `pip install jedi`  and `pip install pip install 'python-language-server[yapf]'`. On the bash shell I can call pyls for example: `pyls --version` (its on PATH)`.

EDIT: I'm actually seeing this same error with `js-langserver` as well. I'm calling it the same way but as told in https://github.com/tbodt/js-langserver, that is `js-langserver --stdio`.

**Comment by joaotavora** [comment]
>  On the bash shell I can call pyls for example: pyls --version (its on PATH)`.

The bash shell is one process, the Emacs process is another process. Emacs consults _its_ value of the _environment variable_ `PATH` for finding programs and it also consults the _lisp variable_ `exec-path` for finding programs. `pyls` is not being found in either of those.  Ask in some Emacs forum how to best setup `exec-path` _or_ `PATH` in Emacs to find the same programs that `bash` does. A little googling brought me [here](https://emacs.stackexchange.com/a/553/2478)...

It could be as easy as putting `(add-to-list 'exec-path "/path/to/py-l-asses-dir")` in your `.emacs` file. It could work fine or you might consider this to be brittle in the future (say, in case you move `pyls` around or want to switch to another version).

**Comment by avocadoras** [comment]
Thanks @joaotavora. I followed your advice and Pyls works... js-langserver does not work, however.... I know the README does not state it's supported. Anyhow, this is my error:
```
Debugger entered--Lisp error: (error "[eglot] -32603: Request initialize failed with message: Cannot convert undefined or null to object")
  signal(error ("[eglot] -32603: Request initialize failed with message: Cannot convert undefined or null to object"))
  error("[eglot] %s" "-32603: Request initialize failed with message: Cannot convert undefined or null to object")
  eglot--error("-32603: Request initialize failed with message: Cannot convert undefined or null to object")
  eglot--connect(js-mode (transient . "/Users/jr/Desktop/") eglot-lsp-server ("js-langserver" "--stdio"))
  eglot(js-mode (transient . "/Users/jr/Desktop/") eglot-lsp-server ("js-langserver" "--stdio") t)
  funcall-interactively(eglot js-mode (transient . "/Users/jr/Desktop/") eglot-lsp-server ("js-langserver" "--stdio") t)
  call-interactively(eglot record nil)
  command-execute(eglot record)
  execute-extended-command(nil "eglot" "eglo")
  funcall-interactively(execute-extended-command nil "eglot" "eglo")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

Would it ever get any support? It would be nice to have the option for untyped javascript.

**Comment by joaotavora** [comment]
Apparently `js-langserver` is complaining that eglot sent it an invalid initialization message. But from your log I can't tell what the complaint points to. Can you share the contents of the `*eglot events*` buffer?

**Comment by avocadoras** [comment]
Here it goes
`*EGLOT events*`

```
client-request (id:1) Sun Sep 22 17:21:55 2019:
(:jsonrpc "2.0" :id 1 :method "initialize" :params
          (:processId 1275 :rootPath "/Users/jr/Desktop/" :rootUri "file:///Users/jr/Desktop/" :initializationOptions nil :capabilities
                      (:workspace
                       (:applyEdit t :executeCommand
                                   (:dynamicRegistration :json-false)
                                   :workspaceEdit
                                   (:documentChanges :json-false)
                                   :didChangeWatchedFiles
                                   (:dynamicRegistration t)
                                   :symbol
                                   (:dynamicRegistration :json-false))
                       :textDocument
                       (:synchronization
                        (:dynamicRegistration :json-false :willSave t :willSaveWaitUntil t :didSave t)
                        :completion
                        (:dynamicRegistration :json-false :completionItem
                                              (:snippetSupport :json-false)
                                              :contextSupport t)
                        :hover
                        (:dynamicRegistration :json-false)
                        :signatureHelp
                        (:dynamicRegistration :json-false)
                        :references
                        (:dynamicRegistration :json-false)
                        :definition
                        (:dynamicRegistration :json-false)
                        :documentSymbol
                        (:dynamicRegistration :json-false :symbolKind
                                              (:valueSet
                                               [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26]))
                        :documentHighlight
                        (:dynamicRegistration :json-false)
                        :codeAction
                        (:dynamicRegistration :json-false :codeActionLiteralSupport
                                              (:codeActionKind
                                               (:valueSet
                                                ["quickfix" "refactor" "refactor.extract" "refactor.inline" "refactor.rewrite" "source" "source.organizeImports"])))
                        :formatting
                        (:dynamicRegistration :json-false)
                        :rangeFormatting
                        (:dynamicRegistration :json-false)
                        :rename
                        (:dynamicRegistration :json-false)
                        :publishDiagnostics
                        (:relatedInformation :json-false))
                       :experimental nil)))

server-reply (id:1) ERROR Sun Sep 22 17:21:57 2019:
(:jsonrpc "2.0" :id 1 :error
          (:code -32603 :message "Request initialize failed with message: Cannot convert undefined or null to object"))

internal Sun Sep 22 17:21:57 2019:
(:message "Connection state changed" :change "killed: 9\n")


----------b---y---e---b---y---e----------
```

`*EGLOT output*` is empty...

**Comment by lljr** [comment]
@joaotavora did you ever get time to look into this issue? It'd be great to see untyped JS support in eglot... I still can't connect to js-langserver with `M-x eglot` and then `js-langserver --stdio`

**Comment by joaotavora** [comment]
I don't know where the error reported by the `js-langserver` is coming from, but maybe this very simple patch would fix it.  Can you try it?
```diff
diff --git a/eglot.el b/eglot.el
index a4ba1f9..5b73a83 100644
--- a/eglot.el
+++ b/eglot.el
@@ -581,7 +581,7 @@ treated as in `eglot-dbind'."
              :rangeFormatting    `(:dynamicRegistration :json-false)
              :rename             `(:dynamicRegistration :json-false)
              :publishDiagnostics `(:relatedInformation :json-false))
-            :experimental (list))))
+            :experimental eglot--{})))
 
 (defclass eglot-lsp-server (jsonrpc-process-connection)
   ((project-nickname
```

**Comment by fbergroth** [comment]
`js-langserver` seems broken to me. When I gave it a try It first crashed if it couldn't find a `.tern-project` file (specifying `plugins`), and later on crashed trying to find eslint relative to the file I was editing.

**Comment by lljr** [comment]
@fbergroth why not submit an issue on their repo? https://github.com/tbodt/js-langserver

**Comment by lljr** [comment]
@joaotavora that did not fix it I think it's the same error
```
client-request (id:1) Mon Aug 31 15:03:42 2020:
(:jsonrpc "2.0" :id 1 :method "initialize" :params
          (:processId 7166 :rootPath "/tmp/" :rootUri "file:///tmp/" :initializationOptions nil :capabilities
                      (:workspace
                       (:applyEdit t :executeCommand
                                   (:dynamicRegistration :json-false)
                                   :workspaceEdit
                                   (:documentChanges :json-false)
                                   :didChangeWatchedFiles
                                   (:dynamicRegistration t)
                                   :symbol
                                   (:dynamicRegistration :json-false)
                                   :configuration t)
                       :textDocument
                       (:synchronization
                        (:dynamicRegistration :json-false :willSave t :willSaveWaitUntil t :didSave t)
                        :completion
                        (:dynamicRegistration :json-false :completionItem
                                              (:snippetSupport :json-false)
                                              :contextSupport t)
                        :hover
                        (:dynamicRegistration :json-false :contentFormat
                                              ["markdown" "plaintext"])
                        :signatureHelp
                        (:dynamicRegistration :json-false :signatureInformation
                                              (:parameterInformation
                                               (:labelOffsetSupport t)))
                        :references
                        (:dynamicRegistration :json-false)
                        :definition
                        (:dynamicRegistration :json-false)
                        :declaration
                        (:dynamicRegistration :json-false)
                        :implementation
                        (:dynamicRegistration :json-false)
                        :typeDefinition
                        (:dynamicRegistration :json-false)
                        :documentSymbol
                        (:dynamicRegistration :json-false :symbolKind
                                              (:valueSet
                                               [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26]))
                        :documentHighlight
                        (:dynamicRegistration :json-false)
                        :codeAction
                        (:dynamicRegistration :json-false :codeActionLiteralSupport
                                              (:codeActionKind
                                               (:valueSet
                                                ["quickfix" "refactor" "refactor.extract" "refactor.inline" "refactor.rewrite" "source" "source.organizeImports"])))
                        :formatting
                        (:dynamicRegistration :json-false)
                        :rangeFormatting
                        (:dynamicRegistration :json-false)
                        :rename
                        (:dynamicRegistration :json-false)
                        :publishDiagnostics
                        (:relatedInformation :json-false))
                       :experimental nil)))

server-reply (id:1) ERROR Mon Aug 31 15:03:42 2020:
(:jsonrpc "2.0" :id 1 :error
          (:code -32603 :message "Request initialize failed with message: Cannot convert undefined or null to object"))

internal Mon Aug 31 15:03:42 2020:
(:message "Connection state changed" :change "killed\n")


----------b---y---e---b---y---e----------
```

**Comment by joaotavora** [comment]
I suspect you didn't compile the definition after you applied the patch, otherwise `:experimental nil` wouldn't display in this way in the events buffer.

**Comment by lljr** [comment]
@joaotavora I did , I tried again and look 
```
client-request (id:1) Mon Aug 31 16:34:43 2020:
(:jsonrpc "2.0" :id 1 :method "initialize" :params
          (:processId 7217 :rootPath "/tmp/" :rootUri "file:///tmp/" :initializationOptions nil :capabilities
                      (:workspace
                       (:applyEdit t :executeCommand
                                   (:dynamicRegistration :json-false)
                                   :workspaceEdit
                                   (:documentChanges :json-false)
                                   :didChangeWatchedFiles
                                   (:dynamicRegistration t)
                                   :symbol
                                   (:dynamicRegistration :json-false)
                                   :configuration t)
                       :textDocument
                       (:synchronization
                        (:dynamicRegistration :json-false :willSave t :willSaveWaitUntil t :didSave t)
                        :completion
                        (:dynamicRegistration :json-false :completionItem
                                              (:snippetSupport :json-false)
                                              :contextSupport t)
                        :hover
                        (:dynamicRegistration :json-false :contentFormat
                                              ["markdown" "plaintext"])
                        :signatureHelp
                        (:dynamicRegistration :json-false :signatureInformation
                                              (:parameterInformation
                                               (:labelOffsetSupport t)))
                        :references
                        (:dynamicRegistration :json-false)
                        :definition
                        (:dynamicRegistration :json-false)
                        :declaration
                        (:dynamicRegistration :json-false)
                        :implementation
                        (:dynamicRegistration :json-false)
                        :typeDefinition
                        (:dynamicRegistration :json-false)
                        :documentSymbol
                        (:dynamicRegistration :json-false :symbolKind
                                              (:valueSet
                                               [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26]))
                        :documentHighlight
                        (:dynamicRegistration :json-false)
                        :codeAction
                        (:dynamicRegistration :json-false :codeActionLiteralSupport
                                              (:codeActionKind
                                               (:valueSet
                                                ["quickfix" "refactor" "refactor.extract" "refactor.inline" "refactor.rewrite" "source" "source.organizeImports"])))
                        :formatting
                        (:dynamicRegistration :json-false)
                        :rangeFormatting
                        (:dynamicRegistration :json-false)
                        :rename
                        (:dynamicRegistration :json-false)
                        :publishDiagnostics
                        (:relatedInformation :json-false))
                       :experimental #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8125 data
                                                   ()))))

server-reply (id:1) ERROR Mon Aug 31 16:34:43 2020:
(:jsonrpc "2.0" :id 1 :error
          (:code -32603 :message "Request initialize failed with message: Cannot convert undefined or null to object"))

internal Mon Aug 31 16:34:43 2020:
(:message "Connection state changed" :change "killed\n")


----------b---y---e---b---y---e----------
```
I evaluated the expression with `C-x C-e` after I saved the change

**Comment by fbergroth** [comment]
> @fbergroth why not submit an issue on their repo? https://github.com/tbodt/js-langserver

It was already fixed in https://github.com/tbodt/js-langserver/pull/5, but it hasn't been published to npm.

**Comment by joaotavora** [comment]
@lljr please try again with this patch:

```diff
diff --git a/eglot.el b/eglot.el
index a4ba1f9..f2faef5 100644
--- a/eglot.el
+++ b/eglot.el
@@ -508,7 +508,7 @@ treated as in `eglot-dbind'."
 
 (cl-defgeneric eglot-initialization-options (server)
   "JSON object to send under `initializationOptions'"
-  (:method (_s) nil)) ; blank default
+  (:method (_s) eglot--{})) ; blank default
 
 (cl-defgeneric eglot-register-capability (server method id &rest params)
   "Ask SERVER to register capability METHOD marked with ID."
@@ -581,7 +581,7 @@ treated as in `eglot-dbind'."
              :rangeFormatting    `(:dynamicRegistration :json-false)
              :rename             `(:dynamicRegistration :json-false)
              :publishDiagnostics `(:relatedInformation :json-false))
-            :experimental (list))))
+            :experimental eglot--{})))
 
 (defclass eglot-lsp-server (jsonrpc-process-connection)
   ((project-nickname
```

**Comment by lljr** [comment]
`eglot-register-capatability` looks like this for me 
```elisp
(cl-defgeneric eglot-register-capability (server method id &rest params)
  "Ask SERVER to register capability METHOD marked with ID."
  (:method
   (_s method _id &rest _params)
   (eglot--warn "Server tried to register unsupported capability `%s'"
                method)))
```

changing `eglot-initialization-options` only still won't connect
```
client-request (id:1) Tue Sep  1 10:20:59 2020:
(:jsonrpc "2.0" :id 1 :method "initialize" :params
          (:processId 3235 :rootPath "/tmp/" :rootUri "file:///tmp/" :initializationOptions nil :capabilities
                      (:workspace
                       (:applyEdit t :executeCommand
                                   (:dynamicRegistration :json-false)
                                   :workspaceEdit
                                   (:documentChanges :json-false)
                                   :didChangeWatchedFiles
                                   (:dynamicRegistration t)
                                   :symbol
                                   (:dynamicRegistration :json-false)
                                   :configuration t)
                       :textDocument
                       (:synchronization
                        (:dynamicRegistration :json-false :willSave t :willSaveWaitUntil t :didSave t)
                        :completion
                        (:dynamicRegistration :json-false :completionItem
                                              (:snippetSupport :json-false)
                                              :contextSupport t)
                        :hover
                        (:dynamicRegistration :json-false :contentFormat
                                              ["markdown" "plaintext"])
                        :signatureHelp
                        (:dynamicRegistration :json-false :signatureInformation
                                              (:parameterInformation
                                               (:labelOffsetSupport t)))
                        :references
                        (:dynamicRegistration :json-false)
                        :definition
                        (:dynamicRegistration :json-false)
                        :declaration
                        (:dynamicRegistration :json-false)
                        :implementation
                        (:dynamicRegistration :json-false)
                        :typeDefinition
                        (:dynamicRegistration :json-false)
                        :documentSymbol
                        (:dynamicRegistration :json-false :symbolKind
                                              (:valueSet
                                               [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26]))
                        :documentHighlight
                        (:dynamicRegistration :json-false)
                        :codeAction
                        (:dynamicRegistration :json-false :codeActionLiteralSupport
                                              (:codeActionKind
                                               (:valueSet
                                                ["quickfix" "refactor" "refactor.extract" "refactor.inline" "refactor.rewrite" "source" "source.organizeImports"])))
                        :formatting
                        (:dynamicRegistration :json-false)
                        :rangeFormatting
                        (:dynamicRegistration :json-false)
                        :rename
                        (:dynamicRegistration :json-false)
                        :publishDiagnostics
                        (:relatedInformation :json-false))
                       :experimental nil)))

server-reply (id:1) ERROR Tue Sep  1 10:21:01 2020:
(:jsonrpc "2.0" :id 1 :error
          (:code -32603 :message "Request initialize failed with message: Cannot convert undefined or null to object"))

internal Tue Sep  1 10:21:01 2020:
(:message "Connection state changed" :change "killed\n")


----------b---y---e---b---y---e----------
```

**Comment by fbergroth** [comment]
@lljr did you even check what I linked?

>           (:code -32603 :message "Request initialize failed with message: Cannot convert undefined or null to object"))

> It was already fixed in [tbodt/js-langserver#5](https://github.com/tbodt/js-langserver/pull/5), but it hasn't been published to npm.

Which states:
> Fix `TypeError: Cannot convert undefined or null to object` error

**Comment by joaotavora** [comment]
> eglot-register-capatability looks like this for me

@lljr you have do to both changes.  Never mind, I've publish a branch you can try with hopefully the correct `eglot.el`.

**Comment by fbergroth** [comment]
Anyway, it'll work if you `npm install -g git+https://github.com/tbodt/js-langserver`. `js-langserver` seems to only grab the root path from initialization.

**Comment by joaotavora** [comment]
> Anyway, it'll work if you npm install -g git+https://github.com/tbodt/js-langserver. js-langserver seems to only grab the root path from initialization.

Tagging this "server bug"

**Comment by lljr** [comment]
@fbergroth I did but I thought the issue was that it'd error out when .tern-project was not in the root directory. I installed it like you said and it's working. BTW, do you know why the binary is not in `~/node_modules/.bin`? I'm using NVM and it got sent somewhere else. I only need to add the nvm version directory to path to have `js-langserver` available. 

@joaotavora thanks for helping me out. It's working. Does eglot support auto completion? I'm not seeing it right now.
