### ISSUE TITLE
Failed to activate company-math and company-ispell when using eglot, texlab, and company. 

### ISSUE THREAD

**Issue by hongyi-zhao** [joaotavora/eglot#708]
On Ubuntu 20.04, I use the self-compiled git master version of Emacs and the following configuration to do the testing:

```emacs-lisp
;;Bootstrap straight
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))
(straight-use-package 'use-package)
(setq straight-use-package-by-default t)


;Using AUCTeX from local Git repo without installation
;https://github.com/raxod502/straight.el/issues/800#issuecomment-862165317
(straight-use-package
 `(auctex :type git :host nil :repo "https://git.savannah.gnu.org/git/auctex.git"
    :pre-build ,(pcase system-type
                (`berkeley-unix '("gmake"))
                (_ '(
                    `("bash" "-c" "cd" ,(straight--repos-dir "auctex"))
                    ("./autogen.sh")
                    ("./configure" "--without-texmf-dir" "--with-lispdir=.") 
                    ("make")
                    )))))

     (setq TeX-data-directory (straight--repos-dir "auctex")
           TeX-lisp-directory TeX-data-directory)                   
    
; Or set the following variable via custom-set-variables in the opened buffer by the following command.
; M-x describe-variable RET preview-TeX-style-dir RET
;`(preview-TeX-style-dir ,(concat ".:" (straight--repos-dir "auctex") "latex:"))
(setq preview-TeX-style-dir (concat ".:" (straight--repos-dir "auctex") "latex:"))

(load "auctex.el" nil t t) 
(load "preview-latex.el" nil t t)

(setq TeX-auto-save t)
(setq TeX-parse-self t)
(setq-default TeX-master nil)
         
(use-package eglot
  :hook 
  ((TeX-mode . eglot-ensure))
  :config
  ;  (setq eglot-confirm-server-initiated-edits nil)

  ;;; ensure we don't use digestif server, which is far less than texlab on features and characteristics.
  ;(delete (assoc '(tex-mode context-mode texinfo-mode bibtex-mode)
  ;               eglot-server-programs) eglot-server-programs)

  ;;; ensure texlab is set as the server.
  (add-to-list 'eglot-server-programs
             '((latex-mode tex-mode context-mode texinfo-mode bibtex-mode) . ("texlab"))))

(use-package company
  :hook
  (TeX-mode . company-mode)
  :custom
  ;https://github.com/company-mode/company-mode/issues/14#issuecomment-290261406
  ; Do not downcase the returned candidates automatically
  (company-dabbrev-downcase nil) 
  (company-idle-delay 0) 
  (company-minimum-prefix-length 1))

(use-package company-math)
(defun my-latex-mode-setup ()
  (setq-local company-math-allow-unicode-symbols-in-faces (quote (tex-math font-latex-math-face)))

  (setq-local company-backends
               (append '((company-math-symbols-latex
                          company-math-symbols-unicode
                          company-latex-commands 
                          company-capf
                          company-ispell
;                          company-abbrev
;                          company-bbdb
;                          company-dabbrev
;                          company-dabbrev-code
;                          company-files
;                          company-keywords
;                          company-semantic
                           ))
                       company-backends)))
(add-hook 'LaTeX-mode-hook 'my-latex-mode-setup)
```
But I find that the above configuration failed to activate the company-math and company-ispell for LaTeX environment, as shown below:

![image](https://user-images.githubusercontent.com/11155854/123372878-f9676880-d5b6-11eb-89e0-290cd271a12b.png)

Any hints for this problem?

Regards,
HY

**Comment by dgutov** [comment]
Diag shows that `company-backends` is set to a different value: `(company-capf)`.

Why? Probably because Eglot changes its value.

Try `(add-to-list 'eglot-stay-out-of 'company)`.

**Comment by joaotavora** [comment]
> Try (add-to-list 'eglot-stay-out-of 'company).

Yes, this is the correct action. Be aware you're now responsible for managing `company-capf` in the `company-backends` list, Eglot is no longer managing that part of the buffer for you.

**Comment by hongyi-zhao** [comment]
Thanks a lot. I try to use the following configuration, and it really does the trick:
```emacs-lisp
(use-package eglot
  :hook 
  ((TeX-mode . eglot-ensure))
  :config
  (add-to-list 'eglot-stay-out-of 'company)
  (add-to-list 'eglot-server-programs
             '((latex-mode tex-mode context-mode texinfo-mode bibtex-mode) . ("texlab"))))
```
![image](https://user-images.githubusercontent.com/11155854/123448234-46762980-d60d-11eb-8af3-5abe7e3017f6.png)

**Comment by dgutov** [comment]
@joaotavora BTW, now that `company-clang` is behind `company-capf` in `company-backends` by default, you can probably remove this change of settings: Eglot should work well with the default config.

**Comment by joaotavora** [comment]
If you happen to use Eglot + other servers, this affects them too.  Recently the C++/C modes `clangd` server had some problems where some Company backend would interfere with `company-capf`.  I suppose they have been fixed.

**Comment by joaotavora** [comment]
ah, I was just commenting about that.  I think it's safest to keep this for a while.

**Comment by hongyi-zhao** [comment]
But I also find that there are some commands still can't be completed, as shown below.

The `\bra` command which is defined in `braket` package can't be completed:
 
![image](https://user-images.githubusercontent.com/11155854/123453038-9f47c100-d611-11eb-828c-6535e7706df0.png)

The `\href` command which is defined in `hyperref` package can't be completed:

![image](https://user-images.githubusercontent.com/11155854/123453082-acfd4680-d611-11eb-8172-dbbb56b16d24.png)

**Comment by joaotavora** [comment]
> But I also find that there are some commands still can't be completed, as shown below.

I didn't have a change to comment on this, but it looks like you completely skipped the issue reporting template.  If you wish an issue to be analysed, you may not do that.  Open a new issue and describe everything accurately as requested.  If you can't do that for one reason or another, it's better to open a new discussion item, as the template will advise.

**Comment by hongyi-zhao** [comment]
Yep. This issue was created from a [blank](https://github.com/joaotavora/eglot/issues/new) one. I'll try to use the template to report the above-mentioned problem in a new issue.

**Comment by hongyi-zhao** [comment]
Another problem is the above configuration can do the partial match search, say, when I input `\arrow`, I want to see all the LaTeX commands which includes `arrow` in it.
